import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script';
import Link from 'next/link';
import {useUser} from '@auth0/nextjs-auth0/client';
import Navbar from '../componenets/navbar';
var roleID = 0;
const Races = ({ races }) => {
    const{user, error, isLoading} = useUser();
    const raceForm = <div></div>;
    const getDataFromDatabase = async () => {
        const response = await fetch(`http://localhost:3000/api/raceForm`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(user)
        });
    
        if (!response.ok) {
            throw new Error(`Error: ${response.status}`);
        }
        const person = await response.json();
       roleID = person[0].id ;
       if(roleID == "1" || roleID == "2"){
        console.log("here");
           raceForm = <a className={styles.card} href = "/raceForm"><h2 >Create Race</h2></a>;
           console.log(raceForm);
       }
        return person[0];
    }
    const navigationBar = Navbar();
    var x = Object.keys(races).length;
    const raceList = [];
    for(var key  = 0; key < x;key++){
        raceList[key] = races[key];
    }
    const displayedRaces = displayRaces(raceList);
    if(user && !isLoading){
    return (
            <div className={styles.container}>
                <header className ={styles.header}>
                    <title>Races</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <Script id = "4" src=
    "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
                    </Script>
                    <link
                        rel="stylesheet"
                        href=
    "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/>
                    <Script id = "5"src=
    "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js">
                    </Script>
                    {navigationBar}
                </header>
                <Script
                        src="https://connect.facebook.net/en_US/sdk.js"
                        strategy="lazyOnload"
                        onLoad={() =>
                            {
                                const person = getDataFromDatabase();
                            }
                        }
                    />
                <main className={styles.main}> 
                    <div class="container">
                        <h1 className = {styles.jumbotron}>All in Run</h1>
                    </div>
                    <div>
                        <table className= {styles.racesTable}>
                            <thead >
                                <tr>
                                    <th>Name</th>
                                    <th>Date</th>
                                    <th>Location</th>
                                    <th>Length</th>
                                    <th>Contact Info</th>

                                </tr>
                            </thead>
                            <tbody id = "races">
                                {displayedRaces}
    
                            </tbody>
                        </table>
                    </div>
                       {raceForm}
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                        >
                        Powered by Power{' '}
                        <span className={styles.logo}>
                        </span>
                    </a>
                </footer>
            </div>
            )
    }
    else{
        return (
            <div className={styles.container}>
                <header className ={styles.header}>
                    <title>Races</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <Script id = "2"src=
    "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
                    </Script>
                    <link
                        rel="stylesheet"
                        href=
    "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/>
                    <Script  id = "1"src=
    "https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js">
                    </Script>
                    {navigationBar}
                </header>
                <main className={styles.main}> 
                    <div class="container">
                        <h1 className = {styles.jumbotron}>All in Run</h1>
                    </div>
                    <div>
                        <table className= {styles.racesTable}>
                            <thead >
                                <tr>
                                    <th>Name</th>
                                    <th>Date</th>
                                    <th>Location</th>
                                    <th>Length</th>
                                    <th>Contact Info</th>

                                </tr>
                            </thead>
                            <tbody id = "races">
                                {displayedRaces}
    
                            </tbody>
                        </table>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                        >
                        Powered by Power{' '}
                        <span className={styles.logo}>
                        </span>
                    </a>
                </footer>
            </div>
            )
    }
}

export async function getServerSideProps(context) {
    const races = await fetch(`http://localhost:3000/api/races`);
    const data = await races.json();
    if (!data) {
        return {
            notFound: true
        };
    }

    return {
        props: { races: data }
    };
}
const RaceDisplay = ({race}) => {
    let display = new Date(race.raceDate);
    return (<tr>
    <td>{race.raceName}</td>
    <td>{display.getMonth()+1}/{display.getDate()}/{display.getFullYear()}</td>
    <td>{race.raceLocation}</td>
    <td>{race.raceLength}km</td>
    <td>{race.Signup}</td>
    </tr>);
}
const displayRaces = ( raceArray ) => { 
    return (
      (raceArray || []).map(race => <RaceDisplay key={race.raceID} race={race} />)
    );
   }
export default Races;